package:
  name: py_wake
  version: {{ environ.get('VERSION', '0.0.0') }} # does not work anymore not sure why

source:
  path: ../

build:
  number: 0
  script: pip install --no-deps .
  skip: True # [py<37]
  noarch: python

requirements:
  # If adding new requirements be sure to also add to setup.py
  run:
    - autograd
    - h5netcdf
    - matplotlib
    - netcdf4
    - numpy
    - python
    - pyyaml
    - scipy
    - scikit-learn # loads
    - tensorflow # loads
    - tqdm
    - xarray
  host:
    - python
    - setuptools
test:
  imports:
    - py_wake